name: amd64 deb11 iso

on:
  push:
    paths:
    - '*.sh'
    - 'preseed.cfg'
    - 'Makefile'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools cpio xorriso curl

      - name: Init
        run: make init

      - name: Build iso
        env: 
          DEBIAN_VERSION: 11.2.0
        run: make build-amd64